### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mkz212**
small fixes and expandable sections where needed

### CODE REVIEW

**Review by donavanbecker — COMMENTED** [review]
sorry, I think this looks good the way it is already.

**Comment by mkz212** [comment]
And that's why I love Homebridge and Homebridge UI - that even the smallest and cosmetic change is checked and evaluated.

I thought that before the release of Homebridge 2.0.0 (and with it probably and the premiere of the Homebridge UI release containing some major changes) it would be worth refreshing these pages a little.

- In my opinion, the pages are too long, so I introduced expandable sections. 
- The photo at the beginning is embedded in such a way that the text travels.
- The Community section should be lower.
- The Why Homebridge paragraph is outdated (there are already many HomeKit devices and people still want to use Homebridge for many reasons).

But I don't insist...

**Comment by mkz212** [comment]
I've improved a lot now.

**Comment by bwp91** [comment]
@mkz212 please can you update from develop so it's easier to see the changes you have made?
+ there is a conflict

**Comment by mkz212** [comment]
> @mkz212 please can you update from develop so it's easier to see the changes you have made?
> 
> * there is a conflict

Done. #3669

**Pull request closed without merging**
