### PR TITLE
New Option "-X" for multiple instances

### PR DESCRIPTION
**Pull request by seydx**
A new option has been added (**-X**) that allows only certain plugins to be loaded to avoid huge memory usage

**Example** (/etc/default/homebridge-instance)

```
# Defaults / Configuration options for homebridge
# The following settings tells homebridge where to find the config.json file and where to persist the data (i.e. pairing and others)
HOMEBRIDGE_OPTS=-U /var/homebridge-instance -X homebridge-alexa

# If you uncomment the following line, homebridge will log more 
# You can display this via systemd's journalctl: journalctl -f -u homebridge
# DEBUG=*
```
_(i.e. this will only load homebridge-alexa)_

Adding the plugin name after -X allows only to load the given plugin, you can also list several plugins (you just have to separate it with a comma, like **-X homebridge-alexa,homebridge-hue** etc.)

Another advantage is that your homebridge instances will load noticeably faster, feels three times faster than without "-X" AND in my case I have 30% less memory usage than without "-X"

The plugins are loaded "globally", so it will be always possible with "-g" to continue installing or updating plugins

The -X option just insert the added plugin name(s) to the already existing paths, so it works on every system

### CODE REVIEW

**Comment by m4d-maNu** [comment]
Great

**Comment by Nastras** [comment]
Yaehhh man,

Thank you very much, that you've made this great feature so fast. Please add this Option!

**Comment by Nastras** [comment]
#1864

**Comment by maikburd** [comment]
I completely agree! Please add this Feature to Homebridge!

**Comment by Heiliger85** [comment]
Great idea. I hope it will come in next version of Homebridge.

**Comment by theo-69** [comment]
Really Great!

**Comment by det-box** [comment]
Hello,
I think the Ide is great especially for multible instances.

Please take it to the HB

Thank you

**Comment by Kohle81** [comment]
Great idea, please add this to the homebridge! 👍

**Comment by theo-69** [comment]
is there a way to install it already?

**Comment by theo-69** [comment]
@nfarina a merge would be great, waiting for this future to to problems with one plugin.

**Comment by SeydX** [comment]
@KhaosT 

Is the method with passing paths into config.json not "too late" for homebridge? 
The config.json is only loaded after all plugins of homebridge have been loaded or am I wrong?

An argument passed in on launch prevent homebridge to load any other plugins which is listed after -X

**Comment by theo-69** [comment]
@KhaosT I think if someone can handle several instances he can handle -X ;-)

**Comment by Nastras** [comment]
@KhaosT Can you tell us what your next plan is for this pull request? Will he be taken over?
Or should @Sydex rebuild it for the config.json? What about his guess that the config.json loads too late?

Many Thanks!

Greeting Nastra

**Comment by NSCHI** [comment]
like this idea, need it in homebridge.

**Comment by Razeeer** [comment]
I would also be very happy about this feature in the official Homebridge. Please take it.

**Comment by theo-69** [comment]
@KhaosT so why still no pull

**Comment by KhaosT** [comment]
I still think this should live in config file instead of a launch parameter. Regarding the order of operation, I mean we can change that if necessary. I’ll try to write something later today and see how it goes.

**Comment by SeydX** [comment]
that sounds good, but as i said, to get the advantages i listed above, homebridge should check first which plugins we only want to load before loading all installed plugins

**Comment by ebaauw** [comment]
I would prefer a config.json solution as well, over a command-line option.  This would make for simpler system management, as all plugins would still be installed in one place, and only the configuration needs to be changed between instances.

Rather than introducing a new key, would it be possible to use the existing `platform` and `accessory` keys?  Homebridge would derive the plugin directory from config.json, rather than through `registerPlatform()` or `registerAccessory()`.  I’m not sure I oversee the full consequences of this, but at least:
- In config.json, one would specify the plugin suffix rather than the plugin name, e.g. `”platform”: “xxx”` for plugin `homebridge-xxx`;
- The name parameter to `registerPlatform()` and `registerAccessory()` would become obsolete;
- `cachedAccessories` would need to hold the platform directory suffix rather than the platform name.

**Comment by cubilon** [comment]
I agree with @ebaauw. a config.json solution would be a better choice.

**Comment by theo-69** [comment]
Even with -x solution the plugins are still installed in the same place. Its just a edition to the already existing way to load plugins. For now I think it would be the best solution. Maybe for later it should be on the to do list.

**Comment by r32er** [comment]
Great idea! i hope it will be added to the homebridge!

**Comment by Nastras** [comment]
That is really a shame. I thought about the last answer from @KhaosT

>   I'll try to write something later today and see how it goes.

The now speed in the topic comes but unfortunately it does not seem to be the case.

Maybe we have to ask the boss .-)
@nfarina @KhaosT 
What is the current state of affairs on the topic?

**Pull request closed without merging**
