### PR TITLE
Convert project to TypeScript

### LINKED ISSUE #1576: Migrate code to Typescript
To improve stability and maintainability.

### PR DESCRIPTION
**Pull request by hassankhan**
Fixes #1576.

This is a rough first-pass at converting the codebase to use ES6 classes and import/exports, and very basic types.

I also tried to use as many types from `hap-nodejs` as I could, however the types from there are written in an _interesting_ way, something I'd like to fix in the future as well.

I've tried running it and it seems to be working for me, unfortunately I don't have a Homebridge setup so it would be great if people could test this branch against their setups to ensure everything still works.

Code-wise, its not idiomatic TypeScript, I've had to `ts-ignore` things like [seemingly incorrect](https://github.com/nfarina/homebridge/compare/master...hassankhan:typescript?expand=1#diff-043e5f2990afccaa2259a67167fda9a6R19) [usage of classes](https://github.com/nfarina/homebridge/compare/master...hassankhan:typescript?expand=1#diff-417383ffc31047d42b6a3f9fccf11455R259).

Also in the `User.config()` method, I couldn't figure out how the `Config` object appears. I've currently [disabled that particular check](https://github.com/nfarina/homebridge/compare/master...hassankhan:typescript#diff-63b1341d67c89fe5db05236331f216edR20) to allow `tsc` to compile the code.

Please let me know if there's anything else I can/should do - I feel like more work could be done towards making the codebase use more advanced Typescript features (like public/private accessors, generics) but could cause compatibility issues/breakages for plugins relying on "internal" APIs.

### CODE REVIEW

**Comment by Kosta-Github** [comment]
any updates on this? 👍

**Comment by codyc1515** [comment]
I agree this should really be a higher priority. We are failing behind quite far on the HAP-NodeJS versions.

**Comment by KhaosT** [comment]
I think the plan to adopt hap-nodejs v0.5.x will be decoupled from converting the project to TypeScript. Both Nick and I are kinda busy with other work (or life) related stuff these days, reviewing a completely rewrite of the project will take a while, and may introduce some unexpected behavior changes...

**Comment by plainsane** [comment]
but i think im liking what you have in the form of admin characteristic validation in hap v0.5.x.  any plans to move up to that version even if it is not in the form of a full rewrite?

**Comment by donavanbecker** [comment]
Closing in favor of #2476, which combiners this PR #2266 and #2358.

**Pull request closed without merging**
