### PR TITLE
Support HomeKit Secure Video

### PR DESCRIPTION
**Pull request by california444**
# Support HomeKit Secure Video

## :recycle: Current situation
Support for HomeKit Secure Video will be added to HAP NodeJS with [PR904](https://github.com/homebridge/HAP-NodeJS/pull/904).

- [ ]  **WORK IN PROGRESS until [PR904](https://github.com/homebridge/HAP-NodeJS/pull/904) gets merged **

## :bulb: Proposed solution
This PR exposes added types and classes for Secure Video from HAP to be used in homebridge plugins

### Problem that is solved
Provide a description and link issues that are solved

### Implications
*Describe the implications, e.g. refactoring*

## :heavy_plus_sign: Additional Information
*Provide some additional information if possible*

### Testing
*tested locally*

### Reviewer Nudging
*Where should the reviewer start, where is a good entry point?*

### CODE REVIEW

**Review by codyc1515 — APPROVED** [review]
Working very well with the Scrypted plug-in.

**Comment by Stetocasa** [comment]
Any news about this request?

**Comment by fate8383** [comment]
We are all waiting impatiently.

**Comment by california444** [comment]
HAP NodeJS PR904 is not yet merged :-(

**Comment by evenstay** [comment]
> HAP NodeJS [PR904](https://github.com/homebridge/HAP-NodeJS/pull/904) is not yet merged :-(

[PR904](https://github.com/homebridge/HAP-NodeJS/pull/904) is closed.

[PR920](https://github.com/homebridge/HAP-NodeJS/pull/920) appears to be taking over where 904 left off.

**Comment by manualmanul** [comment]
FYI, [PR920](https://github.com/homebridge/HAP-NodeJS/pull/920) has been merged.

**Comment by Supereg** [comment]
Closed in favor of #3056

**Pull request closed without merging**
